all_asset_paths = {
    'traffic_light': './assets/traffic_light.png',
    'grass': './assets/grass_0.png',
    'road': './assets/road.png',
    'building': './assets/building_0.png',
    'car': './assets/car_0.png',
    'road_cross': './assets/road_cross.png',
    'road_turn': './assets/road_turn.png',
    'road_end': './assets/road_end.png',
    'parking_center': './assets/parking_center.png',
    'parking_corner': './assets/parking_corner.png',
    'parking_side': './assets/parking_side.png',
    'parking_double': './assets/parking_double.png',
    'parking_bulge': './assets/parking_bulge.png',
    'parking_mark': './assets/parking_mark.png',
    'parking_single': './assets/parking_single.png',
    'sidewalk_end': './assets/sidewalk_end.png',
    'sidewalk_flip': './assets/sidewalk_flip.png',
    'sidewalk_corner': './assets/sidewalk_corner.png',
    'sidewalk_corner_end': './assets/sidewalk_corner_end.png',
    'sidewalk_trio': './assets/sidewalk_trio.png',
    'sidewalk_universal': './assets/sidewalk_universal.png',
    'sidewalk_corner_independent': './assets/sidewalk_corner_independent.png',
    'sidewalk_trio_fork': './assets/sidewalk_trio_fork.png',
    'sidewalk_center': './assets/sidewalk_center.png',
    'sidewalk_corner_small': './assets/sidewalk_corner_small.png',
    'sidewalk_side': './assets/sidewalk_side.png', '404': './assets/404.png'
}
